title = "Richard Voigtmann"
description = "Personal notes and experiments."
theme = "duckquill"

base_url = "https://blog.drvlabs.de"
compile_sass = true
build_search_index = true

generate_feeds = false
feed_filenames = ["atom.xml"]

taxonomies = [{ name = "tags", feed = true }]

[markdown]
smart_punctuation = true
bottom_footnotes = true
github_alerts = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[search]
index_format = "fuse_json"

[extra]
accent_color = "#256a81" #"#808080" #"#ff7800" #
accent_color_dark = "#4146c5" #"#424242" #"#ffa348" #
neutral_background = true
#bundled_fonts = true
styles = ["nav-search.css", "crt.css", "duckquill-fixes.css"]
scripts = ["code-copy.js", "prefetch-links.js"]
show_copy_button = false
show_reading_time = true
show_share_button = false
show_backlinks = true

[extra.nav]
show_feed = false
show_theme_switcher = true
home_label = "About"
links = [{ url = "@/blog/_index.md", name = "Blog" }]

[extra.footer]
links = []
show_copyright = true
